spring:
  application:
    name: api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
        debug: true
server:
  error:
    include-message: ALWAYS

logging.level:
  org.springframework.security: TRACE
  org.springframework.web: DEBUG

springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED}

jasypt:
  encryptor:
    password: mySecretKeys

pseudo:
  mapping:
    file: data/mappings.enc
  key: j0rqaGbymsASTTKdeBUwNnArEG1JH40O

mail:
  from: ${EMAIL_FROM}
  verification-base-url: ${EMAIL_VERIFICATION_BASE_URL}

app-env:
  mode: ${APP_ENV}
  cors:
    allowed-origin: ${CORS_ALLOWED_ORIGIN}

prod:
  admin-username: ${PROD_ADMIN_USERNAME}
  admin-password: ${PROD_ADMIN_PASSWORD}
